import {describe,it,expect} from 'vitest';
import {clientReportTask,sandboxTasks,sandboxAvailability,validatePlan,compileMap,createSandboxSession} from './planning';
import {RuleSchema,type WorkMap} from '../shared/contracts';
const quote='Jonas only does external client work from 13:00 to 17:00. Mornings he covers the support hotline, which is not in the calendar.';
const map=(startHour=13,endHour=17):WorkMap=>({id:'map',version:1,status:'confirmed',teachBack:quote,rules:[{id:'window',kind:'client_work_window',title:'Client window',explanation:quote,expertQuote:quote,evidenceIds:['frame','answer'],parameters:{person:'Jonas',startHour,endHour}}]});
const tasks=()=>{const report=clientReportTask();Object.assign(report,{assignee:'Jonas',start:'2026-10-08T08:00:00+02:00',end:'2026-10-08T12:00:00+02:00',decision:'Schedule'});return [...sandboxTasks().filter(t=>t.id!=='atlas'),report];};
describe('expert-confirmed client work window',()=>{
 it('rejects incomplete or reversed policy parameters',()=>{const r=map().rules[0];expect(RuleSchema.safeParse({...r,parameters:{}}).success).toBe(false);expect(RuleSchema.safeParse({...r,parameters:{person:'Jonas',startHour:17,endHour:13}}).success).toBe(false);});
 it('contains no hotline or afternoon restriction in held-out task facts',()=>{expect(JSON.stringify(clientReportTask())).not.toMatch(/hotline|afternoon|13:00/);expect(clientReportTask().timeWindow).toBe('Flexible');});
 it('blocks an otherwise valid morning only after the expert teaches the rule',()=>{const proposal=tasks();expect(validatePlan(proposal,sandboxAvailability(),{...map(),rules:[]}).allowed).toBe(true);const result=validatePlan(proposal,sandboxAvailability(),map());expect(result.findings).toHaveLength(1);expect(result.findings[0]).toMatchObject({ruleId:'window',taskIds:['client-report'],expertQuote:quote});Object.assign(proposal.at(-1)!,{start:'2026-10-08T13:00:00+02:00',end:'2026-10-08T17:00:00+02:00'});expect(validatePlan(proposal,sandboxAvailability(),map()).allowed).toBe(true);});
 it('changes behavior with reviewed hours and does not restrict internal work',()=>{const proposal=tasks();expect(validatePlan(proposal,sandboxAvailability(),map(8,17)).allowed).toBe(true);proposal.at(-1)!.external=false;expect(validatePlan(proposal,sandboxAvailability(),map()).allowed).toBe(true);});
 it('uses Berlin wall clock even when timestamps are UTC and rejects overrun',()=>{const proposal=tasks();Object.assign(proposal.at(-1)!,{start:'2026-10-08T11:00:00Z',end:'2026-10-08T15:00:00Z'});expect(validatePlan(proposal,sandboxAvailability(),map()).allowed).toBe(true);expect(validatePlan(proposal,sandboxAvailability(),map(13,16)).findings.some(f=>f.ruleId==='window')).toBe(true);});
 it('requires resolution of the revealed client case',()=>{const proposal=tasks();proposal.at(-1)!.decision='Hold';expect(validatePlan(proposal,sandboxAvailability(),map(),{requireUrgentResolution:true}).allowed).toBe(false);});
 it('compiles the window only from selected expert answers and fails if hours are absent',()=>{const s=createSandboxSession('test','sandbox');s.evidence=[{id:'frame',sessionId:s.id,epoch:0,at:'now',kind:'frame',text:'Synthetic frame'}];s.answers=Array.from({length:6},(_,i)=>({id:String(i),stage:i<3?'capture':'debrief',question:`Question ${i}`,answer:quote,evidenceIds:['frame'],ruleKinds:['client_work_window'],guardrail:i===2}));expect(compileMap(s).rules[0].parameters).toEqual({person:'Jonas',startHour:13,endHour:17});s.answers.forEach(a=>a.answer='Client work in afternoons.');expect(()=>compileMap(s)).toThrow(/explicit window/);});
});
