import {expect,it} from 'vitest';
import {InterviewDraft} from './interview-draft';
it('pins the answered question and observed frame when the AI asks its next question',()=>{const draft=new InterviewDraft();draft.receiveQuestion({text:'Why Jonas?',frameId:'observed-original',origin:'vision'});expect(draft.receiveAnswer('The client specifically requires Jonas.')).toBe(true);expect(draft.receiveQuestion({text:'What about overlap?',frameId:'later-screen',origin:'voice'})).toBe('queued');expect(draft.question?.text).toBe('Why Jonas?');expect(draft.question?.frameId).toBe('observed-original');expect(draft.receiveAnswer('Words after the agent changed the question.')).toBe(false);expect(draft.beginSave()).toEqual({question:'Why Jonas?',answer:'The client specifically requires Jonas.',frameId:'observed-original'});draft.finishSave(true);expect(draft.useNext()).toBe(true);expect(draft.question?.frameId).toBe('later-screen');});
it('does not lose an unsaved answer when saving fails, or attach speech arriving during the save',()=>{const draft=new InterviewDraft();draft.manualQuestion('Why?', 'frame');draft.manualAnswer('Expert words.', 'frame');const snapshot=draft.beginSave();expect(draft.receiveAnswer('Late speech')).toBe(false);draft.manualQuestion('Wrong replacement','other');expect(draft.question?.text).toBe(snapshot.question);draft.finishSave(false);expect(draft.answer).toBe('Expert words.');expect(draft.question?.frameId).toBe('frame');});
it('allows a requested voice rephrasing only before the expert starts answering and preserves its observed frame',()=>{const draft=new InterviewDraft();draft.receiveQuestion({text:'Why this assignment?',frameId:'observed',origin:'vision'});draft.receiveQuestion({text:'Why assign this task to Jonas?',frameId:'newer',origin:'voice'},true);expect(draft.question?.frameId).toBe('observed');draft.receiveAnswer('Client restriction.');draft.receiveQuestion({text:'A later rephrase?',frameId:'later',origin:'voice'},true);expect(draft.question?.text).toBe('Why assign this task to Jonas?');expect(draft.next).toBe(null);});
it('keeps unassociated speech in the transcript instead of inventing a question',()=>{const draft=new InterviewDraft();expect(draft.receiveAnswer('Speaking before the prompt.')).toBe(false);expect(draft.answer).toBe('');draft.manualAnswer('Reviewed typed words','frame');draft.receiveQuestion({text:'Later question?',frameId:'later',origin:'voice'});expect(draft.question).toBe(null);expect(draft.next?.text).toBe('Later question?');});

it('retains an explicitly selected screen moment when it is chosen before typing the question',()=>{const draft=new InterviewDraft();draft.relink('reviewed-original');draft.manualAnswer('Typed reasoning before prompt','new-screen');draft.manualQuestion('The reviewed question?','latest-screen');expect(draft.frameId).toBe('reviewed-original');expect(draft.beginSave().frameId).toBe('reviewed-original');});

it('retains every distinct queued question through a save or explicit current-draft discard',()=>{const draft=new InterviewDraft();draft.manualQuestion('First?','one');draft.manualAnswer('First answer','one');draft.receiveQuestion({text:'Second?',frameId:'two',origin:'voice'});draft.receiveQuestion({text:'Third?',frameId:'three',origin:'voice'});draft.receiveQuestion({text:'Second?',frameId:'two',origin:'voice'});expect(draft.queuedCount).toBe(2);draft.discardCurrent();expect(draft.useNext()).toBe(true);expect(draft.question?.text).toBe('Second?');expect(draft.next?.text).toBe('Third?');});
