import React, { useEffect, useId, useRef, useState } from 'react';
import type { Availability, Task } from '../shared/contracts';
import { DateField } from './date-field';
import './notion-planner.css';

type PlannerProps = { tasks: Task[]; availability: Availability[]; onChange: (tasks: Task[]) => void; readOnly?: boolean; mode?: 'capture' | 'teach'; saved?: boolean; fullViewControls?: React.ReactNode };
type View = 'table' | 'calendar' | 'timeline';
const people: Task['assignee'][] = ['Unassigned', 'Lea', 'Jonas', 'Mira'];
const decisions: Task['decision'][] = ['Schedule', 'Split', 'Request information', 'Escalate', 'Hold'];
const priorities = ['Urgent', 'High', 'Normal', 'Low'];
const format = (value: string | null, options: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString('en-GB', { ...options, timeZone: 'Europe/Berlin' }) : 'Not scheduled';
const dayKey = (value: string | Date) => { const parts = new Intl.DateTimeFormat('en-GB', { timeZone: 'Europe/Berlin', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date(value)); const part = (type: string) => parts.find(p => p.type === type)?.value ?? ''; return `${part('year')}-${part('month')}-${part('day')}`; };
const calendarDate = (value: number) => { const [year, month, day] = dayKey(new Date(value)).split('-').map(Number); return new Date(Date.UTC(year, month - 1, day, 12)); };
const berlinMidnight = (value: Date) => { const key = dayKey(value); const utc = Date.parse(`${key}T00:00:00Z`); const offset = new Intl.DateTimeFormat('en-GB', { timeZone: 'Europe/Berlin', timeZoneName: 'shortOffset' }).formatToParts(new Date(utc)).find(p => p.type === 'timeZoneName')?.value.match(/GMT([+-])(\d+)(?::(\d+))?/); const minutes = offset ? (Number(offset[2]) * 60 + Number(offset[3] ?? 0)) * (offset[1] === '-' ? -1 : 1) : 0; return utc - minutes * 60000; };

/** A controlled draft editor. Persistence and policy checks belong to the host. */
export function NotionPlanner({ tasks, availability, onChange, readOnly = false, mode = 'capture', saved = false, fullViewControls }: PlannerProps) {
  const [expanded, setExpanded] = useState(false);
  const plannerRoot = useRef<HTMLElement | null>(null);
  useEffect(() => {
    if (!expanded || !plannerRoot.current) return;
    const root = plannerRoot.current;
    const previousFocus = document.activeElement as HTMLElement | null;
    const backgrounds: {element: HTMLElement; inert: boolean}[] = [];
    for (let branch: HTMLElement | null = root; branch?.parentElement && branch.parentElement !== document.body; branch = branch.parentElement) {
      for (const sibling of branch.parentElement.children) {
        if (sibling !== branch && sibling instanceof HTMLElement) {
          backgrounds.push({element: sibling, inert: sibling.inert});
          sibling.inert = true;
        }
      }
    }
    root.querySelector<HTMLButtonElement>('.np-focus-button')?.focus();
    const keyboard = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !root.querySelector('.np-detail')) { event.preventDefault(); setExpanded(false); }
      if (event.key === 'Tab') {
        const focusable = [...root.querySelectorAll<HTMLElement>('button, input, select, textarea, summary, a[href], [tabindex="0"]')].filter(element => !element.hasAttribute('disabled') && element.getClientRects().length && getComputedStyle(element).visibility !== 'hidden');
        const first = focusable[0], last = focusable.at(-1);
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
        else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
      }
    };
    document.addEventListener('keydown', keyboard);
    return () => { document.removeEventListener('keydown', keyboard); backgrounds.forEach(({element, inert}) => {element.inert = inert;}); previousFocus?.focus(); };
  }, [expanded]);
  const [view, setView] = useState<View>('table');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [weekOffset, setWeekOffset] = useState(0);
  const [monthOffset, setMonthOffset] = useState(0);
  const opener = useRef<HTMLElement | null>(null);
  const closeButton = useRef<HTMLButtonElement | null>(null);
  const openTask = (id: string) => { opener.current = document.activeElement as HTMLElement; setSelectedId(id); };
  const closeTask = () => { setSelectedId(null); opener.current?.focus(); };
  useEffect(() => { if (!selectedId) return; closeButton.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setSelectedId(null); opener.current?.focus(); } }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape); }, [selectedId]);
  const [query, setQuery] = useState('');
  const capacityId = useId(), tasksId = useId();
  const navigate = (id: string) => document.getElementById(id)?.scrollIntoView({block:'start'});
  const [navigationTarget,setNavigationTarget]=useState<string|null>(null);
  useEffect(()=>{if(navigationTarget){navigate(navigationTarget);setNavigationTarget(null);}},[navigationTarget,view]);
  const selected = tasks.find(t => t.id === selectedId);
  const visible = tasks.filter(t => `${t.title} ${t.assignee} ${t.skill} ${t.customer} ${t.description} ${t.trainingStage}`.toLowerCase().includes(query.toLowerCase()));
  const update = (id: string, patch: Partial<Task>) => { if (!readOnly) onChange(tasks.map(t => t.id === id ? { ...t, ...patch } : t)); };
  const timestamps = [...tasks.map(t => Date.parse(t.deadline)), ...availability.map(a => Date.parse(a.start))].filter(Number.isFinite);
  const monday = calendarDate(timestamps.length ? Math.min(...timestamps) : Date.now());
  monday.setUTCDate(monday.getUTCDate() - (monday.getUTCDay() + 6) % 7 + weekOffset * 7);
  const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(monday); d.setUTCDate(d.getUTCDate() + i); return d; });
  const deadlines = tasks.map(t => Date.parse(t.deadline)).filter(Number.isFinite);
  const month = calendarDate(deadlines.length ? Math.min(...deadlines) : monday.getTime());
  month.setUTCDate(1); month.setUTCMonth(month.getUTCMonth() + monthOffset);
  const calendarStart = new Date(month); calendarStart.setUTCDate(1 - (month.getUTCDay() + 6) % 7);
  const calendarDays = Array.from({ length: 42 }, (_, i) => { const d = new Date(calendarStart); d.setUTCDate(d.getUTCDate() + i); return d; });
  const personList = [...new Set(availability.map(a => a.person))];
  const flagLabels = (t: Task) => [t.priority === 0 ? 'Urgent' : '', t.customerPreference.endsWith(' only') ? 'Customer restricted' : '', t.external ? 'Review required' : '', t.focus ? 'Focus work' : '', t.dependencyStatus !== 'Ready' ? t.dependencyStatus : ''].filter(Boolean);
  const assigneeField = (t: Task) => <select aria-label={`${t.title} assignee`} disabled={readOnly} value={t.assignee} onChange={e => update(t.id, { assignee: e.target.value as Task['assignee'] })}>{people.map(p => <option key={p}>{p}</option>)}</select>;
  const dateField = (t: Task, key: 'start' | 'end' | 'reviewStart' | 'reviewEnd' | 'followUpCheckpoint' | 'dependencyAvailableAt', label: string) => <fieldset className="np-date" disabled={readOnly}><DateField value={t[key]} label={`${t.title} ${label}`} onCommit={value => update(t.id, { [key]: value })} /></fieldset>;
  const taskCard = (t: Task) => <button key={t.id} type="button" className="np-task-card" onClick={() => openTask(t.id)}><strong>{t.title}</strong><span>{t.assignee} · {t.effort}h</span><span>Due {format(t.deadline)}</span><span>{format(t.start, { hour: '2-digit', minute: '2-digit' })}{t.end ? ` – ${format(t.end, { hour: '2-digit', minute: '2-digit' })}` : ''}</span><span className="np-tags">{flagLabels(t).map(f => <span className="np-tag" key={f}>{f}</span>)}</span></button>;
  return <section ref={plannerRoot} className={`np-root ${expanded ? 'np-expanded' : ''}`} aria-label="Decision Echo Planning Sandbox">
    <aside className="np-sidebar"><div className="np-workspace-name"><span className="np-workspace-icon">D</span> Decision Echo</div><div className="np-sidebar-caption">Planning workspace</div><nav aria-label="Planning sections"><button type="button" onClick={() => navigate(tasksId)} className="np-sidebar-link np-current">Task planning</button><button type="button" onClick={() => navigate(capacityId)} className="np-sidebar-link">Team capacity</button><button className="np-sidebar-link" type="button" onClick={() => {setView('calendar');setNavigationTarget(tasksId);}}>Deadline calendar</button></nav><div className="np-sidebar-note">Demo workspace · fictional team data<br />{mode === 'teach' ? 'Learner practice' : 'Expert demonstration'}<br />{saved ? 'Saved plan · read only.' : 'Changes remain a local draft.'}</div></aside>
    <div className="np-page"><div className="np-topbar"><span>Decision Echo <span aria-hidden="true">/</span> <b>Weekly planning</b></span><button className="np-focus-button" type="button" aria-pressed={expanded} onClick={() => setExpanded(v => !v)}>{expanded ? 'Exit full view' : 'Focus planner'}</button><span className="np-draft-badge">{saved ? 'Saved · Confirmed' : readOnly ? 'Read only' : 'Draft'}</span></div><div className="np-page-content"><h2 className="np-page-title">Weekly planning</h2><p className="np-page-description">Assign work, reserve review time, and keep the week feasible.</p><div className="np-callout"><span>{mode === 'teach' ? 'Use the expert’s confirmed Work Map to plan this new case.' : 'Show how you plan and explain your choices.'} {saved ? 'This confirmed plan is saved and read only.' : mode === 'teach' ? 'Changes stay unsaved until you check and approve the plan.' : 'Planner edits stay local; review and save your explanations in the session panel.'}</span></div>
    <section id={capacityId} className="np-capacity-section"><h3>Team capacity</h3><div className="np-table-scroll"><table className="np-capacity-table"><thead><tr><th>Person</th><th>Skills</th><th>Available windows</th></tr></thead><tbody>{personList.map(person => <tr key={person}><td><span className={`np-person np-person-${person.toLowerCase()}`}>{person}</span></td><td>{[...new Set(availability.filter(a => a.person === person).flatMap(a => a.skill))].join(', ')}</td><td><div className="np-capacity-windows">{availability.filter(a => a.person === person).map((a, i) => <span key={i}>{format(a.start, { weekday: 'short', hour: '2-digit', minute: '2-digit' })}–{format(a.end, { hour: '2-digit', minute: '2-digit' })}</span>)}</div></td></tr>)}</tbody></table></div></section>
    <section id={tasksId} className="np-task-section"><h3>Incoming Tasks</h3><div className="np-database-toolbar"><div className="np-view-tabs" aria-label="Task views">{(['table', 'calendar', 'timeline'] as View[]).map(v => <button key={v} type="button" aria-pressed={view === v} className={view === v ? 'np-view-active' : ''} onClick={() => setView(v)}>{v === 'table' ? '▦ Table' : v === 'calendar' ? '▦ Calendar' : '☰ Timeline'}</button>)}</div><input className="np-search" aria-label="Search tasks" placeholder="Search tasks…" value={query} onChange={e => setQuery(e.target.value)} /></div>
    {view === 'table' && <div className="np-table-scroll"><table className="np-task-table"><thead><tr><th>Task</th><th>Customer</th><th>Training stage</th><th>Priority</th><th>Person</th><th>Start</th><th>End</th><th>Deadline</th><th>Effort</th><th>Required skill</th><th>Dependency</th><th>Flags</th><th>Decision</th><th>Review owner</th><th>Review status</th><th>Plan status</th><th>Final confirmed</th></tr></thead><tbody>{visible.map(t => <tr key={t.id}><td><button className="np-title-button" type="button" onClick={() => openTask(t.id)}><span aria-hidden="true">▤</span> {t.title} <span className="np-open-icon" aria-hidden="true">↗</span></button><small>{t.customerPreference}</small></td><td>{t.customer || 'Not specified'}</td><td><span className="np-tag">{t.trainingStage || 'Not set'}</span></td><td><span className={`np-tag ${t.priority === 0 ? 'np-tag-yellow' : ''}`}>{priorities[t.priority]}</span></td><td>{assigneeField(t)}</td><td>{dateField(t, 'start', 'start')}</td><td>{dateField(t, 'end', 'end')}</td><td className="np-nowrap">{format(t.deadline)}</td><td>{t.effort}h</td><td><span className="np-tag">{t.skill}</span></td><td><span className={`np-tag ${t.dependencyStatus !== 'Ready' ? 'np-tag-orange' : 'np-tag-green'}`}>{t.dependencyStatus}</span></td><td><div className="np-tags">{flagLabels(t).map(f => <span className="np-tag np-tag-yellow" key={f}>{f}</span>)}</div></td><td><select aria-label={`${t.title} decision`} value={t.decision} disabled={readOnly} onChange={e => update(t.id, { decision: e.target.value as Task['decision'] })}>{decisions.map(d => <option key={d}>{d}</option>)}</select></td><td><select aria-label={`${t.title} review owner`} disabled={readOnly} value={t.reviewOwner} onChange={e => update(t.id, { reviewOwner: e.target.value as Task['reviewOwner'] })}><option>None</option><option>Mira</option></select></td><td><span className="np-tag">{t.reviewStatus}</span></td><td><span className={`np-tag ${saved ? 'np-tag-green' : ''}`}>{saved ? 'Saved' : 'Draft'}</span></td><td><span aria-label={`${t.title} final confirmed: ${saved ? 'yes' : 'no'}`}>{saved ? '☑' : '☐'}</span></td></tr>)}</tbody></table></div>}
    {view === 'calendar' && <><div className="np-view-heading">{format(month.toISOString(), { month: 'long', year: 'numeric' })}<span>Task deadlines · Europe/Berlin</span><div className="np-period-nav"><button type="button" aria-label="Previous month" onClick={() => setMonthOffset(n => n - 1)}>‹</button><button type="button" aria-label="Next month" onClick={() => setMonthOffset(n => n + 1)}>›</button></div></div><div className="np-calendar">{calendarDays.map(day => <div className={`np-calendar-day ${day.getUTCMonth() !== month.getUTCMonth() ? 'np-outside-month' : ''}`} key={day.toISOString()}><div className="np-calendar-date">{format(day.toISOString(), { weekday: 'short' })}<strong>{day.getUTCDate()}</strong></div>{visible.filter(t => dayKey(t.deadline) === dayKey(day)).map(taskCard)}</div>)}</div><div className="np-unscheduled"><h4>Not scheduled ({visible.filter(t => !t.start).length})</h4><div>{visible.filter(t => !t.start).map(taskCard)}</div></div></>}
    {view === 'timeline' && <><div className="np-view-heading">Week of {format(monday.toISOString(), { day: 'numeric', month: 'long' })}<span>Production and review · Europe/Berlin</span><div className="np-period-nav"><button type="button" aria-label="Previous week" onClick={() => setWeekOffset(n => n - 1)}>‹</button><button type="button" aria-label="Next week" onClick={() => setWeekOffset(n => n + 1)}>›</button></div></div><div className="np-table-scroll"><table className="np-timeline-table"><thead><tr><th>Task</th>{days.map(day => <th key={day.toISOString()}>{format(day.toISOString(), { weekday: 'short', day: 'numeric' })}</th>)}</tr></thead><tbody>{visible.map(t => <tr key={t.id}><td><button className="np-title-button" type="button" onClick={() => openTask(t.id)}>{t.title}</button><small>{t.assignee} · {t.effort}h{!t.start ? ' · Not scheduled' : ''}</small></td>{days.map(day => <td key={day.toISOString()}>{t.start && t.end && new Date(t.start).getTime() < berlinMidnight(new Date(day.getTime() + 86400000)) && new Date(t.end).getTime() > berlinMidnight(day) && <button className="np-timeline-block" onClick={() => openTask(t.id)}>{t.assignee}<small>{format(t.start, { hour: '2-digit', minute: '2-digit' })}–{format(t.end, { hour: '2-digit', minute: '2-digit' })}</small></button>}{t.reviewStart && dayKey(t.reviewStart) === dayKey(day) && <button className="np-timeline-block np-review-block" onClick={() => openTask(t.id)}>Review · {t.reviewOwner}<small>{format(t.reviewStart, { hour: '2-digit', minute: '2-digit' })}–{format(t.reviewEnd, { hour: '2-digit', minute: '2-digit' })}</small></button>}</td>)}</tr>)}</tbody></table></div></>}
    {!visible.length && <p className="np-empty">No tasks match your search.</p>}<div className="np-database-footer">{tasks.length} tasks · Demo data · Inputs: local time · Calendar: Europe/Berlin{expanded && mode === 'teach' && <div className="np-full-view-note">Review findings and save in the session panel.</div>}</div></section></div></div>
    {selected && <aside className="np-detail" aria-label={`${selected.title} details`}><div className="np-detail-top"><span>Task properties</span><button ref={closeButton} type="button" aria-label="Close task details" onClick={closeTask}>×</button></div><h3>{selected.title}</h3><p className="np-detail-note">{saved ? 'This confirmed plan is saved. All properties are read only.' : 'Source facts are read only. Edit the planning draft, then check and save in the main workspace.'}</p><div className="np-source-facts"><div className="np-detail-fact">Customer <b>{selected.customer || 'Not specified'}</b></div><div className="np-detail-fact">Description <b>{selected.description || 'Not specified'}</b></div><div className="np-detail-fact">Training stage <b>{selected.trainingStage || 'Not set'}</b></div><div className="np-detail-fact">Time window <b>{selected.timeWindow || 'Not specified'}</b></div><div className="np-detail-fact">Planning week <b>{selected.planningWeek || 'Not specified'}</b></div><div className="np-detail-fact">Dependency <b>{selected.dependency || 'None specified'}</b></div><div className="np-detail-fact">Review status <b>{selected.reviewStatus}</b></div></div><fieldset disabled={readOnly} className="np-detail-fields"><label>Person{assigneeField(selected)}</label><label>Decision<select value={selected.decision} onChange={e => update(selected.id, { decision: e.target.value as Task['decision'] })}>{decisions.map(d => <option key={d}>{d}</option>)}</select></label><div className="np-detail-fact">Priority <b>{priorities[selected.priority]}</b></div><label>Start{dateField(selected, 'start', 'start')}</label><label>End{dateField(selected, 'end', 'end')}</label><div className="np-detail-fact">Deadline <b>{format(selected.deadline)}</b></div><div className="np-detail-fact">Customer requirement <b>{selected.customerPreference}</b></div><div className="np-detail-fact">Dependency status <b>{selected.dependencyStatus}</b></div><div className="np-detail-fact">Dependency available <b>{format(selected.dependencyAvailableAt)}</b></div><label>Review owner<select value={selected.reviewOwner} onChange={e => update(selected.id, { reviewOwner: e.target.value as Task['reviewOwner'] })}><option>None</option><option>Mira</option></select></label><label>Review start{dateField(selected, 'reviewStart', 'review start')}</label><label>Review end{dateField(selected, 'reviewEnd', 'review end')}</label><label>Follow-up owner<input value={selected.followUpOwner} onChange={e => update(selected.id, { followUpOwner: e.target.value })} /></label><label>Follow-up checkpoint{dateField(selected, 'followUpCheckpoint', 'follow-up checkpoint')}</label></fieldset></aside>}
    {expanded && fullViewControls && <div className="np-session-rail" role="region" aria-label="Session controls">{fullViewControls}</div>}
  </section>;
}
