import {afterEach,expect,it,vi} from 'vitest';
import {ObservationQueue,type Observation,type ObservationFrame} from './observation-queue';
const frame=(id:string)=>({frameId:id,epoch:1,image:`synthetic-${id}`});
const result:Observation={question:'Why this visible choice?',ruleKinds:['no_overlap'],guardrail:false};
const flush=async()=>{await Promise.resolve();await Promise.resolve();await Promise.resolve();};
afterEach(()=>vi.useRealTimers());
it('lets every upload complete while a slow observation retains only the latest frame',async()=>{vi.useFakeTimers();vi.setSystemTime(0);let finish!:(r:Observation)=>void;const observed:string[]=[],uploaded:string[]=[];const request=vi.fn((f:{frameId:string},_s:AbortSignal)=>{observed.push(f.frameId);return new Promise<Observation>(resolve=>{finish=resolve;});});const queue=new ObservationQueue({request,onResult:vi.fn(),onError:vi.fn()});for(let i=0;i<5;i++){uploaded.push(String(i));queue.submit(frame(String(i)));await vi.advanceTimersByTimeAsync(2000);}expect(uploaded).toEqual(['0','1','2','3','4']);expect(observed).toEqual(['0']);finish(result);await flush();expect(observed).toEqual(['0','4']);queue.invalidate();});
it('aborts and drops observation results and pending frames on off-record',async()=>{let finish!:(r:Observation)=>void;let signal!:AbortSignal;const onResult=vi.fn(),onError=vi.fn();const request=vi.fn((_f,s:AbortSignal)=>{signal=s;return new Promise<Observation>(resolve=>{finish=resolve;});});const queue=new ObservationQueue({request,onResult,onError});queue.submit(frame('old'));queue.submit(frame('pending'));queue.invalidate();expect(signal.aborted).toBe(true);finish(result);await flush();expect(onResult).not.toHaveBeenCalled();expect(onError).not.toHaveBeenCalled();expect(request).toHaveBeenCalledTimes(1);});
it('enforces two-second minimum cadence after a quick model result',async()=>{vi.useFakeTimers();vi.setSystemTime(0);const request=vi.fn(async(_f:ObservationFrame)=>result);const queue=new ObservationQueue({request,onResult:vi.fn(),onError:vi.fn()});queue.submit(frame('one'));await flush();queue.submit(frame('two'));queue.submit(frame('three'));await vi.advanceTimersByTimeAsync(1999);expect(request).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(1);expect(request).toHaveBeenCalledTimes(2);expect(request.mock.calls[1]?.[0].frameId).toBe('three');queue.invalidate();});
