import {afterEach,describe,expect,it,vi} from 'vitest';
import {VisualCoachQueue,coachMeaning} from './visual-coach';
import type {VisualCoach} from '../shared/contracts';
const input=(frameId:string)=>({frameId,epoch:1,mapVersion:2});
const result=(frameId:string):VisualCoach=>({frameId,at:'2026-10-04T00:00:00Z',mapVersion:2,summary:'A visible assignment may conflict.',concerns:[{ruleId:'required',visibleBasis:'The visible assignee is Lea.',message:'Check the client requirement.',expertQuote:'Jonas only',evidenceIds:['expert-frame']}],nextQuestion:'Who did the client require?',uncertain:true});
const flush=async()=>{await Promise.resolve();await Promise.resolve();await Promise.resolve();};
afterEach(()=>vi.useRealTimers());
describe('visual coach request lifecycle',()=>{
 it('keeps only the latest pending frame and enforces serial five-second cadence',async()=>{vi.useFakeTimers();vi.setSystemTime(0);let finish!:(r:VisualCoach)=>void;const request=vi.fn((_input:{frameId:string},_signal:AbortSignal)=>new Promise<VisualCoach>(resolve=>{finish=resolve;}));const onResult=vi.fn(),onError=vi.fn(),onPending=vi.fn();const queue=new VisualCoachQueue({request,onResult,onError,onPending});queue.submit(input('one'));queue.submit(input('two'));queue.submit(input('three'));expect(request).toHaveBeenCalledTimes(1);finish(result('one'));await flush();expect(onResult).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(4999);expect(request).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(1);expect(request).toHaveBeenCalledTimes(2);expect(request.mock.calls[1]?.[0].frameId).toBe('three');queue.invalidate();});
 it('aborts and discards a late model response after off-record',async()=>{let finish!:(r:VisualCoach)=>void;let signal!:AbortSignal;const onResult=vi.fn(),onError=vi.fn();const queue=new VisualCoachQueue({request:(_i,s)=>{signal=s;return new Promise(resolve=>{finish=resolve;});},onResult,onError,onPending:vi.fn()});queue.submit(input('frame'));queue.invalidate();expect(signal.aborted).toBe(true);finish(result('frame'));await flush();expect(onResult).not.toHaveBeenCalled();expect(onError).not.toHaveBeenCalled();});
 it('surfaces provider errors and rejects a mismatched frame/map without an observation',async()=>{const onResult=vi.fn(),onError=vi.fn();const queue=new VisualCoachQueue({request:async()=>({...result('other'),mapVersion:99}),onResult,onError,onPending:vi.fn()});queue.submit(input('frame'));await flush();expect(onResult).not.toHaveBeenCalled();expect(onError).toHaveBeenCalledTimes(1);queue.invalidate();const failed=new VisualCoachQueue({request:async()=>{throw new Error('Provider unavailable');},onResult,onError,onPending:vi.fn()});failed.submit(input('new'));await flush();expect(onError).toHaveBeenCalledTimes(2);failed.invalidate();});
 it('does not repeat a same frame or identical semantic context on timestamp changes',()=>{const request=vi.fn(async()=>result('frame'));const queue=new VisualCoachQueue({request,onResult:vi.fn(),onError:vi.fn(),onPending:vi.fn()});queue.submit(input('frame'));queue.submit(input('frame'));expect(request).toHaveBeenCalledTimes(1);expect(coachMeaning(result('frame'))).toBe(coachMeaning({...result('new-frame'),at:'later'}));queue.invalidate();});
});
import {interventionFor} from './visual-coach';
describe('visual coach intervention',()=>{
 const grounded=(frameId:string):VisualCoach=>({...result(frameId),uncertain:false});
 it('requests one spoken intervention per newly concerned rule',()=>{const first=interventionFor(grounded('a'),new Set());expect(first?.ruleIds).toEqual(['required']);expect(first?.message).toContain('required');expect(first?.message).not.toContain('Check the client requirement');expect(first?.message).not.toContain('The visible assignee is Lea.');expect(interventionFor(grounded('b'),new Set(first!.ruleIds))).toBeNull();});
 it('stays silent for uncertain observations or frames without concerns',()=>{expect(interventionFor(result('a'),new Set())).toBeNull();expect(interventionFor({...grounded('a'),concerns:[]},new Set())).toBeNull();});
});
