const el=id=>document.getElementById(id);
let connection=null,active=false,epoch=0,tabId=null,timer=null,controller=null,busy=false,lastActivity=0,allowedOrigin=null,generation=0;
const status=text=>el('status').textContent=text;
function baseURL(raw){const u=new URL(raw);if(u.protocol!=='http:'||!['localhost','127.0.0.1'].includes(u.hostname)||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('Use an HTTP loopback origin only');return u.origin;}
async function api(path,body,signal){const r=await fetch(`${connection.base}/api/sessions/${encodeURIComponent(connection.id)}${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${connection.token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal,cache:'no-store',redirect:'error'});if(!r.ok)throw Error(`Workspace request failed (${r.status})`);return r.json();}
async function synchronize(){const s=await api('');if(!s.recording||s.epoch!==epoch){halt();status('Stopped: workspace capture authority changed');return false;}return true;}
function halt(){generation++;active=false;clearInterval(timer);timer=null;controller?.abort();controller=null;busy=false;if(tabId!==null)chrome.tabs.sendMessage(tabId,{type:'capture-disable'}).catch(()=>{});}
async function evidence(kind,text,image){if(!active||busy)return;busy=true;const mine=epoch;const c=new AbortController();controller=c;try{if(!await synchronize())return;const target=await chrome.tabs.get(tabId);if(new URL(target.url).origin!==allowedOrigin){halt();return;}if(!active||mine!==epoch)return;await api('/evidence',{epoch:mine,kind,text,...(image?{image}:{})},c.signal);}catch(e){if(e.name!=='AbortError'){halt();status(e.message);}}finally{if(controller===c){controller=null;busy=false;}}}
chrome.runtime.onMessage.addListener((m,sender)=>{if(m.type==='capture-activity'&&sender.tab?.id===tabId&&active&&Date.now()-lastActivity>500){lastActivity=Date.now();void evidence('activity',String(m.text).slice(0,140));}});
el('start').onclick=async()=>{halt();const attempt=generation;try{
  connection={base:baseURL(el('endpoint').value),id:el('session').value.trim(),token:el('token').value.trim()};el('token').value='';if(!connection.id||!connection.token)throw Error('Session and token required');
  const allowed=new URL(el('origin').value);if(!['http:','https:'].includes(allowed.protocol)||allowed.username||allowed.password)throw Error('Enter a target web origin');
  const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab||new URL(tab.url).origin!==allowed.origin)throw Error('Current tab must match the allowed origin');tabId=tab.id;allowedOrigin=allowed.origin;
  const s=await api('');if(generation!==attempt)return;epoch=s.epoch;if(!s.recording)throw Error('Start recording in the workspace first');
  await chrome.scripting.executeScript({target:{tabId},files:['content.js']});if(generation!==attempt)return;await chrome.tabs.sendMessage(tabId,{type:'capture-enable'});if(generation!==attempt){chrome.tabs.sendMessage(tabId,{type:'capture-disable'}).catch(()=>{});return;}active=true;status('Recording selected tab metadata');
  timer=setInterval(async()=>{if(!active||busy)return;try{if(!await synchronize())return;const t=await chrome.tabs.get(tabId);if(new URL(t.url).origin!==allowed.origin){halt();status('Stopped: selected tab left allowed origin');return;}if(el('frames').checked){const current=await chrome.tabs.query({active:true,windowId:t.windowId});if(current[0]?.id!==tabId)return;const mine=epoch;const image=await chrome.tabs.captureVisibleTab(t.windowId,{format:'jpeg',quality:55});if(active&&epoch===mine)await evidence('frame','Explicitly consented selected-tab frame',image);}}catch(e){halt();status(e.message);}},2000);
}catch(e){halt();status(e.message);}};
el('stop').onclick=async()=>{halt();if(!connection)return;try{const s=await api('');epoch=s.epoch;await api('/recording',{recording:false,epoch});status('Off record: workspace capture stopped');}catch(e){status(`Local capture stopped; workspace pause unconfirmed: ${e.message}`);}};
window.addEventListener('pagehide',()=>{halt();connection=null;});
